### ISSUE TITLE
Summation Test output

### ISSUE THREAD

**Issue by HappyCane** [milcent/benford_py#23]
Hello!
First of all, you did a very good job writing this library. It saves a lot of time for all of us Benford researchers without proper programming education.
I would like to bring to your attention a possible malfunction of the Summation Test function.
When I run it for a multitude of columns with a for loop it plots the histograms at the end, not with the respected tables produced from each separate column. This makes it hard to match each histogram with the column/variable it refers to.
Furthermore, the produced tables are ordered by the F2D column and not the difference column as implied by the title of the table.
I wish you the best!

Edit: Could you please provide some insight about what does the AbsDif represent and how it could be used?

**Comment by milcent** [comment]
Dear HappyCane,
I am sorry to be able to answer you only now.
Due to other commitments, I had been absent to github.
I shall look into it.
As for the AbsDif column, is I remember correctly it is one of the computation steps for the Z-scores.

**Comment by milcent** [comment]
I have not used it in  a for loop with multiple columns.
Can you provide a sample of the code?

**Comment by milcent** [comment]
When we clear this out, we can reopen the issue and try to solve it.
