### ISSUE TITLE
Module's name and changes on pypi

### ISSUE THREAD

**Issue by im-alexandre** [milcent/benford_py#26]
Think changing the name from "benford_py" to simply "benford" is more intuitive, like "pandas", "numpy", etc.

I reinstalled the module, in order to include arc_test function, but it's not updated on Pypi.

**Comment by milcent** [comment]
Indeed, it is not yet updated in the Pipy yet. I have to review some other changes I had made before releasing the next version.

As for the naming, in the Pipy version the lib name is benford_py, but when you install it, it is benford, and to import you type `import benford as bf`, It is like Pytorch (`form torch import ...`) or scikit-learn (`from sklearn import...`)

**Comment by im-alexandre** [comment]
I know, but I meant the name in Pypi. It doesn't see important, but, I think would be better

**Comment by milcent** [comment]
I found a (seemingly empty) benford in Pypi:
https://pypi.org/project/benford/
Maybe we could join forces.

Em sáb, 26 de out de 2019 às 20:59, im-alexandre <notifications@github.com>
escreveu:
