### ISSUE TITLE
mad() got an unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by sebbylim** [milcent/benford_py#34]
Just trying to grab the MAD value for my dataset, but faced this error. [Recently updated to 0.2.5]
Codes are as follow:
import benford as bf
mad1 = bf.mad(rawdata["Gross Total"], test=1)

Traceback (most recent call last):

  File "<ipython-input-5-78c3332e34ab>", line 1, in <module>
    mad1 = bf.mad(rawdata["Gross Total"], test=1)

  File "C:\Users\sebastianlimzj\AppData\Local\Continuum\anaconda3\lib\site-packages\benford\benford.py", line 1362, in mad
    start.first_digits(digs=test, MAD=True, MSE=True, simple=True)

  File "C:\Users\sebastianlimzj\AppData\Local\Continuum\anaconda3\lib\site-packages\benford\benford.py", line 639, in first_digits
    self.MAD = mad(df, test=digs, verbose=self.verbose)

TypeError: mad() got an unexpected keyword argument 'verbose'

**Comment by milcent** [comment]
Thanks for reporting.
This is probably a bug resulting from the deprecation of the `inform` argument in favor of the `verbose`  one, and the latter must have been incorrectly inserted in the `mad()` function.
I will look into it.

**Comment by milcent** [comment]
All should be fine now, in the latest master branch.
It will be in Pypi (pip install) in the next version (0.2.6).
Let me know if there is any other problem.
Cheers

**Comment by milcent** [comment]
Version 0.2.6 now in Pypi
`pip install --upgrade benford_py`
