### ISSUE TITLE
Bug: TypeError when calling 'chi_square' argument

### ISSUE THREAD

**Issue by matrixChimera** [milcent/benford_py#36]
### Bug
''TypeError: 'bool' object is not callable'' when calling 'chi_square' argument→ 
[Bug-TypeError of chi_square.ipynb.zip](https://github.com/milcent/benford_py/files/4467833/Bug-TypeError.of.chi_square.ipynb.zip)

### Platform
MacOS Catalina 10.15.1 
Python 3.7.1
benford-py 0.2.6

**Comment by milcent** [comment]
Thanks for reporting it.
I'll check it out

**Comment by milcent** [comment]
Fixed and included in latest version (0.2.7)
`pip install benford_py`
should deal with it.
Cheers
