### ISSUE TITLE
Files on PyPI don't match the project name

### ISSUE THREAD

**Issue by yurivict** [milcent/benford_py#47]
https://pypi.org/project/benford-py/#files has benford_py-0.3.2.tar.gz while the project is named benford-py.

IMO if you renamed the project, this should affect file names, GH project name, etc, to reduce confusion.

**Comment by milcent** [comment]
Actually the name was alwasy the same as in here: benford_py.
And the installation files follow this pattern.
But in the last release, the PyPi changed it to benford-py.
And the installation with pip seems to work with both (`pip install benford_py` and `pip install benford-py`.
I tried to revert the change in PyPi, without success.
If you know how to do this, please let me know.

**Comment by yurivict** [comment]
I don't know how to change this, but PyPI redirects https://pypi.org/project/benford_py/ -> https://pypi.org/project/benford-py/

As a result, Repology only finds "benford-py": https://repology.org/projects/?search=benford

**Comment by milcent** [comment]
I have file an [issue](https://github.com/pypa/warehouse/issues/8950) in Pypa github.

**Comment by milcent** [comment]
Since both ways work for PyPi, but it normalizes for "-", I have created a twin githhub repo called "benford-py"
