### ISSUE TITLE
summation() unexpected kwarg 'verbose'

### ISSUE THREAD

**Issue by HappyCane** [milcent/benford_py#49]
Hello,
I get this error with the summation() which resembles the closed issue a fellow member had with mad(). Unfortunately, I can't find a way around it.

--Code--

Initialized sequence with 1452 registries.

---------------------------------------------------------------------------

TypeError                                 Traceback (most recent call last)

<ipython-input-100-bd354247349f> in <module>()
      1 #Summation
----> 2 bf.summation(rev['Revenues'],digs=2,show_plot=True)

/usr/local/lib/python3.6/dist-packages/benford/benford.py in summation(data, digs, decimals, sign, top, verbose, show_plot, save_plot, save_plot_kwargs, inform)
   1554                           show_plot=show_plot, save_plot=save_plot,
   1555                           save_plot_kwargs=save_plot_kwargs, ret_df=True)
-> 1556     if verbose == True:
   1557         return data.sort_values('AbsDif', ascending=False)
   1558     else:

TypeError: summation() got an unexpected keyword argument 'verbose'

**Comment by milcent** [comment]
Thanks for posting.
What is you version of the package? The latest?

**Comment by HappyCane** [comment]
Yes! I run it from google colab so I download the last version each time

**Comment by milcent** [comment]
OK.
I will check it out.

**Comment by milcent** [comment]
I think I have fixed it, but am still going to run some tests in the same function and in the more recent parts of the library.
While I don't release another version with the bugfix, you should be able to install it in Colab directly from github, with the command below:
`pip install git+https://github.com/milcent/benford_py.git@hotfix/summ_verbose` 
Let me now if it works.
Cheers,
Milcent

**Comment by HappyCane** [comment]
Yep it works thank you! You do a very good job sir !

**Comment by milcent** [comment]
I have merged it into master, so the pip comand below should also work:
`pip install git+https://github.com/milcent/benford_py.git@master`

**Comment by milcent** [comment]
It is now in v0.3.3 (latest)

**Comment by milcent** [comment]
Might I ask (if you can disclose it) in what field are you using the
package and how the summation test, or any other, for that matter, is
helping you?

Em sáb., 23 de jan. de 2021 às 16:52, Harry Kapnas <notifications@github.com>
escreveu:

**Comment by HappyCane** [comment]
I work as an auditor and I'm experimenting on automated auditing techniques. I find your package very useful whenever I manage to get enough data for the algorithm to be effective.

**Comment by milcent** [comment]
Thanks for sharing.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Em dom., 24 de jan. de 2021 às 15:08, Harry Kapnas <notifications@github.com>
escreveu:
